name = "interaction"
stan_file = "src/stan/model.stan"
data_dir = "data/prepared/interaction"
run_cross_validation = false

[sample_kwargs]
show_progress = true
save_warmup = false
iter_warmup = 2000
iter_sampling = 2000

[sample_kwargs_cross_validation]
chains = 1