name = "interaction_fake_data"
stan_file = "src/stan/model.stan"
data_dir = "data/prepared/fake_interaction"
modes = ["prior", "posterior", "cross_validation"]

[stanc_options]
warn-pedantic = true

[sample_kwargs]
show_progress = true
save_warmup = false
iter_warmup = 2000
iter_sampling = 2000

[sample_kwargs.cross_validation]
chains = 1
