name = "fake_interaction"
stan_file = "multilevel-linear-regression.stan"
prepared_data_dir = "fake_interaction"
stan_input_function = "get_stan_input_interaction"
modes = ["prior", "posterior", "kfold"]

[dims]
b = ["covariate"]
y = ["observation"]
x = ["observation", "covariate"]

[stanc_options]
warn-pedantic = true

[sample_kwargs]
save_warmup = false
iter_warmup = {{ cookiecutter.n_iter_default }}
iter_sampling = {{ cookiecutter.n_iter_default }}

[mode_options.kfold]
n_folds = 5
chains = 1
iter_warmup = {{ cookiecutter.n_iter_default | int // 2 }}
iter_sampling = {{ cookiecutter.n_iter_default | int // 2 }}
