---
title: Cover letter - Bibat, Batteries-included Bayesian analysis template
---

Dear editors

This paper is intended for the machine learning open source software section
of JLMR.

All the authors are aware of this submission and consent to its review by JMLR.

Please find below all the information listed on the relevant JMLR page here
<https://www.jmlr.org/mloss/mloss-info.html>.

Best wishes,
Teddy Groves

## Open source licence

MIT licence: <https://github.com/teddygroves/bibat/LICENSE>

## Web address of the project

<https://github.com/teddygroves/bibat/>

## Software version to be reviewed

0.2.0

## Evidence of active user community

Bibat has 16 GitHub stars and has been actively developed over about three
years. In addition, bibat is a PyOpenSci affiliated package: the PyOpenSci
community provides rigorous peer review (though not publication), publicity,
community engagement and help with software maintenance.

## Suggested reviewers

These people previously reviewed bibat for PyOpenSci and therefore might find it
easy to provide another review:

- Meenal Jhajharia <meenal@mjhajharia.com>
- Oriol Abril Plaza <https://github.com/OriolAbril>
- Alexey Izmailov <alizma@brown.edu>
