on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

name: Render pdfs

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          # To install LaTeX to build PDF book
          tinytex: true

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          to: typst
          path: paper

      - uses: actions/upload-artifact@v4
        with:
          name: pdfs
          path: paper/*.pdf
