# This workflow runs tests using tox.

name: Run tox

on: push

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.3
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.3
    - name: Install bibat
      run: |
        python -m pip install --upgrade pip
        pip install -e .[development]
    - name: Run tox
      run: tox
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
