# This workflow tests whether projects with sphinx documentation work correctly.

name: Test target project docs

on: push

jobs:
  docs:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Set up Python 3.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.12
    - name: Use bibat
      run: copier copy -l -d docs_format=Sphinx --vcs-ref ${{ github.sha }} gh:teddygroves/bibat my_cool_project
    - name: build docs with sphinx
      run: |
        cd my_cool_project
        make env
        sphinx-build docs ./docs/_build/html/
