# This workflow tests whether projects with sphinx documentation work correctly.

name: Test pandoc

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    container: 
      image: pandoc/latex:2.9

    steps:
    - uses: actions/checkout@v2
    - name: Create pdf docs with pandoc
      run: cd {{cookiecutter.repo_name}}/docs && make report
