# This workflow tests whether projects with sphinx documentation work correctly.

name: Test pandoc

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install cookiecutter
      run: pip install cookiecutter
    - name: Use cookiecutter
      run: |
        cookiecutter --no-input --config-file tests/data/example_config.yml .
    - name: Create pdf docs with pandoc
      uses: docker://pandoc/latex:2.9
      run: cd my_cool_project/docs && make report
