# This workflow tests whether projects with sphinx documentation work correctly.

name: Sphinx Check

on: push

jobs:
  docs:
    
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install bibat with development packages
      run: pip install -e .\[development\]
    - name: build docs with sphinx
      run: |
        cd bibat/\{\{cookiecutter.repo_name\}\}
        sphinx-build docs ./docs/_build/html/
